export const WEB3_API_REQUIRED_ENV_VARS = [
  "WALLET_PRIVATE_KEY",
  "THIRDWEB_API_KEY",
  "POSTGRES_HOST",
  "POSTGRES_DATABASE_NAME",
  "POSTGRES_USER",
  "POSTGRES_PASSWORD",
  "POSTGRES_PORT",
  "POSTGRES_USE_SSL",
];

export const WEB3_API_SERVER_ENV_VARS = WEB3_API_REQUIRED_ENV_VARS.concat([
  "OPENAPI_BASE_ORIGIN",
]);
