import type { FastifyInstance } from "fastify";
import { erc721BalanceOf } from "./read/balance-of.js";
import { erc721CanClaim } from "./read/can-claim.js";
import { erc721Get } from "./read/get.js";
import { erc721GetActiveClaimConditions } from "./read/get-active-claim-conditions.js";
import { erc721GetAll } from "./read/get-all.js";
import { erc721GetAllClaimConditions } from "./read/get-all-claim-conditions.js";
import { erc721GetClaimIneligibilityReasons } from "./read/get-claim-ineligibility-reasons.js";
import { erc721GetClaimerProofs } from "./read/get-claimer-proofs.js";
import { erc721GetOwned } from "./read/get-owned.js";
import { erc721IsApproved } from "./read/is-approved.js";
import { erc721SignatureGenerate } from "./read/signature-generate.js";
import { erc721SignaturePrepare } from "./read/signature-prepare.js";
import { erc721TotalClaimedSupply } from "./read/total-claimed-supply.js";
import { erc721TotalCount } from "./read/total-count.js";
import { erc721TotalUnclaimedSupply } from "./read/total-unclaimed-supply.js";
import { erc721burn } from "./write/burn.js";
import { erc721claimTo } from "./write/claim-to.js";
import { erc721lazyMint } from "./write/lazy-mint.js";
import { erc721mintBatchTo } from "./write/mint-batch-to.js";
import { erc721mintTo } from "./write/mint-to.js";
import { erc721SetApprovalForAll } from "./write/set-approval-for-all.js";
import { erc721SetApprovalForToken } from "./write/set-approval-for-token.js";
import { erc721SetClaimConditions } from "./write/set-claim-conditions.js";
import { erc721SignatureMint } from "./write/signature-mint.js";
import { erc721transfer } from "./write/transfer.js";
import { erc721transferFrom } from "./write/transfer-from.js";
import { erc721UpdateClaimConditions } from "./write/update-claim-conditions.js";
import { erc721UpdateTokenMetadata } from "./write/update-token-metadata.js";

export const erc721Routes = async (fastify: FastifyInstance) => {
  // GET
  await fastify.register(erc721Get);
  await fastify.register(erc721GetAll);
  await fastify.register(erc721GetOwned);
  await fastify.register(erc721BalanceOf);
  await fastify.register(erc721IsApproved);
  await fastify.register(erc721TotalCount);
  await fastify.register(erc721TotalClaimedSupply);
  await fastify.register(erc721TotalUnclaimedSupply);
  await fastify.register(erc721CanClaim);
  await fastify.register(erc721GetActiveClaimConditions);
  await fastify.register(erc721GetAllClaimConditions);
  await fastify.register(erc721GetClaimIneligibilityReasons);
  await fastify.register(erc721GetClaimerProofs);

  // POST
  await fastify.register(erc721SetApprovalForAll);
  await fastify.register(erc721SetApprovalForToken);
  await fastify.register(erc721transfer);
  await fastify.register(erc721transferFrom);
  await fastify.register(erc721mintTo);
  await fastify.register(erc721mintBatchTo);
  await fastify.register(erc721burn);
  await fastify.register(erc721lazyMint);
  await fastify.register(erc721claimTo);
  await fastify.register(erc721SignatureGenerate);
  await fastify.register(erc721SignatureMint);
  await fastify.register(erc721SetClaimConditions);
  await fastify.register(erc721UpdateClaimConditions);
  await fastify.register(erc721SignaturePrepare);
  await fastify.register(erc721UpdateTokenMetadata);
};
