import type { FastifyInstance } from "fastify";
import { erc721BalanceOf } from "./read/balance-of";
import { erc721CanClaim } from "./read/can-claim";
import { erc721Get } from "./read/get";
import { erc721GetActiveClaimConditions } from "./read/get-active-claim-conditions";
import { erc721GetAll } from "./read/get-all";
import { erc721GetAllClaimConditions } from "./read/get-all-claim-conditions";
import { erc721GetClaimIneligibilityReasons } from "./read/get-claim-ineligibility-reasons";
import { erc721GetClaimerProofs } from "./read/get-claimer-proofs";
import { erc721GetOwned } from "./read/get-owned";
import { erc721IsApproved } from "./read/is-approved";
import { erc721SignatureGenerate } from "./read/signature-generate";
import { erc721SignaturePrepare } from "./read/signature-prepare";
import { erc721TotalClaimedSupply } from "./read/total-claimed-supply";
import { erc721TotalCount } from "./read/total-count";
import { erc721TotalUnclaimedSupply } from "./read/total-unclaimed-supply";
import { erc721burn } from "./write/burn";
import { erc721claimTo } from "./write/claim-to";
import { erc721lazyMint } from "./write/lazy-mint";
import { erc721mintBatchTo } from "./write/mint-batch-to";
import { erc721mintTo } from "./write/mint-to";
import { erc721SetApprovalForAll } from "./write/set-approval-for-all";
import { erc721SetApprovalForToken } from "./write/set-approval-for-token";
import { erc721SetClaimConditions } from "./write/set-claim-conditions";
import { erc721SignatureMint } from "./write/signature-mint";
import { erc721transfer } from "./write/transfer";
import { erc721transferFrom } from "./write/transfer-from";
import { erc721UpdateClaimConditions } from "./write/update-claim-conditions";
import { erc721UpdateTokenMetadata } from "./write/update-token-metadata";

export const erc721Routes = async (fastify: FastifyInstance) => {
  // GET
  await fastify.register(erc721Get);
  await fastify.register(erc721GetAll);
  await fastify.register(erc721GetOwned);
  await fastify.register(erc721BalanceOf);
  await fastify.register(erc721IsApproved);
  await fastify.register(erc721TotalCount);
  await fastify.register(erc721TotalClaimedSupply);
  await fastify.register(erc721TotalUnclaimedSupply);
  await fastify.register(erc721CanClaim);
  await fastify.register(erc721GetActiveClaimConditions);
  await fastify.register(erc721GetAllClaimConditions);
  await fastify.register(erc721GetClaimIneligibilityReasons);
  await fastify.register(erc721GetClaimerProofs);

  // POST
  await fastify.register(erc721SetApprovalForAll);
  await fastify.register(erc721SetApprovalForToken);
  await fastify.register(erc721transfer);
  await fastify.register(erc721transferFrom);
  await fastify.register(erc721mintTo);
  await fastify.register(erc721mintBatchTo);
  await fastify.register(erc721burn);
  await fastify.register(erc721lazyMint);
  await fastify.register(erc721claimTo);
  await fastify.register(erc721SignatureGenerate);
  await fastify.register(erc721SignatureMint);
  await fastify.register(erc721SetClaimConditions);
  await fastify.register(erc721UpdateClaimConditions);
  await fastify.register(erc721SignaturePrepare);
  await fastify.register(erc721UpdateTokenMetadata);
};
