CREATE TABLE IF NOT EXISTS transactions (
    identifier uuid NOT NULL UNIQUE PRIMARY KEY,
    "walletAddress" VARCHAR(255) NOT NULL,
    "contractAddress" VARCHAR(255) NOT NULL,
    "toAddress" VARCHAR(255),
    "chainId" VARCHAR(255) NOT NULL,
    "extension" VARCHAR(255),
    "submittedTxNonce" BIGINT,
    "txType" VARCHAR(255),
    "txHash" VARCHAR(255),
    "encodedInputData" TEXT,
    "rawFunctionName" TEXT,
    "rawFunctionArgs" TEXT,
    "createdTimestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedTimestamp" TIMESTAMP,
    "txSubmittedTimestamp" TIMESTAMP,
    "txProcessedTimestamp" TIMESTAMP,
    "txRetryTimestamp" TIMESTAMP,
    "txProcessed" BOOLEAN,
    "txSubmitted" BOOLEAN,
    "txMined" BOOLEAN,
    "txErrored" BOOLEAN,
    "gasPrice" VARCHAR(255),
    "gasLimit" VARCHAR(255),
    "maxPriorityFeePerGas" VARCHAR(255),
    "maxFeePerGas" VARCHAR(255),
    "txValue" VARCHAR(100)
);

ALTER TABLE transactions
ALTER COLUMN "rawFunctionArgs" TYPE TEXT,
ALTER COLUMN "extension" TYPE VARCHAR(255),
ALTER COLUMN "submittedTxNonce" TYPE BIGINT,
ALTER COLUMN "walletAddress" TYPE VARCHAR(255),
ALTER COLUMN "toAddress" TYPE VARCHAR(255),
ALTER COLUMN "contractAddress" TYPE VARCHAR(255),
ALTER COLUMN "gasPrice" TYPE VARCHAR(255),
ALTER COLUMN "gasLimit" TYPE VARCHAR(255),
ALTER COLUMN "maxPriorityFeePerGas" TYPE VARCHAR(255),
ALTER COLUMN "maxFeePerGas" TYPE VARCHAR(255),
ALTER COLUMN "txType" TYPE VARCHAR(255),
ADD COLUMN IF NOT EXISTS "deployedContractAddress" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "contractType" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "errorMessage" TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS "txValue" VARCHAR(100) DEFAULT NULL;