CREATE TABLE transactions (
    identifier uuid NOT NULL UNIQUE PRIMARY KEY,
    "walletAddress" VARCHAR(42) NOT NULL,
    "contractAddress" VARCHAR(42) NOT NULL,
    "toAddress" VARCHAR(42),
    "chainId" VARCHAR(255) NOT NULL,
    "extension" VARCHAR(200),
    "submittedTxNonce" BIGINT,
    "txType" VARCHAR(2),
    "txHash" VARCHAR(255),
    "encodedInputData" TEXT,
    "rawFunctionName" TEXT,
    "rawFunctionArgs" TEXT,
    "createdTimestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedTimestamp" TIMESTAMP,
    "txSubmittedTimestamp" TIMESTAMP,
    "txProcessedTimestamp" TIMESTAMP,
    "txRetryTimestamp" TIMESTAMP,
    "txProcessed" BOOLEAN,
    "txSubmitted" BOOLEAN,
    "txMined" BOOLEAN,
    "txErrored" BOOLEAN,
    "gasPrice" VARCHAR(200),
    "gasLimit" VARCHAR(200),
    "maxPriorityFeePerGas" VARCHAR(200),
    "maxFeePerGas" VARCHAR(200)
);
