import type { FastifyInstance } from "fastify";
import { erc1155BalanceOf } from "./read/balance-of";
import { erc1155CanClaim } from "./read/can-claim";
import { erc1155Get } from "./read/get";
import { erc1155GetActiveClaimConditions } from "./read/get-active-claim-conditions";
import { erc1155GetAll } from "./read/get-all";
import { erc1155GetAllClaimConditions } from "./read/get-all-claim-conditions";
import { erc1155GetClaimIneligibilityReasons } from "./read/get-claim-ineligibility-reasons";
import { erc1155GetClaimerProofs } from "./read/get-claimer-proofs";
import { erc1155GetOwned } from "./read/get-owned";
import { erc1155IsApproved } from "./read/is-approved";
import { erc1155SignatureGenerate } from "./read/signature-generate";
import { erc1155TotalCount } from "./read/total-count";
import { erc1155TotalSupply } from "./read/total-supply";
import { erc1155airdrop } from "./write/airdrop";
import { erc1155burn } from "./write/burn";
import { erc1155burnBatch } from "./write/burn-batch";
import { erc1155claimTo } from "./write/claim-to";
import { erc1155lazyMint } from "./write/lazy-mint";
import { erc1155mintAdditionalSupplyTo } from "./write/mint-additional-supply-to";
import { erc1155mintBatchTo } from "./write/mint-batch-to";
import { erc1155mintTo } from "./write/mint-to";
import { erc1155SetApprovalForAll } from "./write/set-approval-for-all";
import { erc1155SetBatchClaimConditions } from "./write/set-batch-claim-conditions";
import { erc1155SetClaimCondition } from "./write/set-claim-conditions";
import { erc1155SignatureMint } from "./write/signature-mint";
import { erc1155transfer } from "./write/transfer";
import { erc1155transferFrom } from "./write/transfer-from";
import { erc1155UpdateClaimConditions } from "./write/update-claim-conditions";
import { erc1155UpdateTokenMetadata } from "./write/update-token-metadata";

export const erc1155Routes = async (fastify: FastifyInstance) => {
  // GET
  await fastify.register(erc1155Get);
  await fastify.register(erc1155GetAll);
  await fastify.register(erc1155GetOwned);
  await fastify.register(erc1155BalanceOf);
  await fastify.register(erc1155IsApproved);
  await fastify.register(erc1155TotalCount);
  await fastify.register(erc1155TotalSupply);
  await fastify.register(erc1155SignatureGenerate);
  await fastify.register(erc1155CanClaim);
  await fastify.register(erc1155GetActiveClaimConditions);
  await fastify.register(erc1155GetAllClaimConditions);
  await fastify.register(erc1155GetClaimerProofs);
  await fastify.register(erc1155GetClaimIneligibilityReasons);

  // POST
  await fastify.register(erc1155airdrop);
  await fastify.register(erc1155burn);
  await fastify.register(erc1155burnBatch);
  await fastify.register(erc1155claimTo);
  await fastify.register(erc1155lazyMint);
  await fastify.register(erc1155mintAdditionalSupplyTo);
  await fastify.register(erc1155mintBatchTo);
  await fastify.register(erc1155mintTo);
  await fastify.register(erc1155SetApprovalForAll);
  await fastify.register(erc1155transfer);
  await fastify.register(erc1155transferFrom);
  await fastify.register(erc1155SignatureMint);
  await fastify.register(erc1155SetClaimCondition);
  await fastify.register(erc1155SetBatchClaimConditions);
  await fastify.register(erc1155UpdateClaimConditions);
  await fastify.register(erc1155UpdateTokenMetadata);
};
