import type { FastifyInstance } from "fastify";
import { erc1155BalanceOf } from "./read/balance-of.js";
import { erc1155CanClaim } from "./read/can-claim.js";
import { erc1155Get } from "./read/get.js";
import { erc1155GetActiveClaimConditions } from "./read/get-active-claim-conditions.js";
import { erc1155GetAll } from "./read/get-all.js";
import { erc1155GetAllClaimConditions } from "./read/get-all-claim-conditions.js";
import { erc1155GetClaimIneligibilityReasons } from "./read/get-claim-ineligibility-reasons.js";
import { erc1155GetClaimerProofs } from "./read/get-claimer-proofs.js";
import { erc1155GetOwned } from "./read/get-owned.js";
import { erc1155IsApproved } from "./read/is-approved.js";
import { erc1155SignatureGenerate } from "./read/signature-generate.js";
import { erc1155TotalCount } from "./read/total-count.js";
import { erc1155TotalSupply } from "./read/total-supply.js";
import { erc1155airdrop } from "./write/airdrop.js";
import { erc1155burn } from "./write/burn.js";
import { erc1155burnBatch } from "./write/burn-batch.js";
import { erc1155claimTo } from "./write/claim-to.js";
import { erc1155lazyMint } from "./write/lazy-mint.js";
import { erc1155mintAdditionalSupplyTo } from "./write/mint-additional-supply-to.js";
import { erc1155mintBatchTo } from "./write/mint-batch-to.js";
import { erc1155mintTo } from "./write/mint-to.js";
import { erc1155SetApprovalForAll } from "./write/set-approval-for-all.js";
import { erc1155SetBatchClaimConditions } from "./write/set-batch-claim-conditions.js";
import { erc1155SetClaimCondition } from "./write/set-claim-conditions.js";
import { erc1155SignatureMint } from "./write/signature-mint.js";
import { erc1155transfer } from "./write/transfer.js";
import { erc1155transferFrom } from "./write/transfer-from.js";
import { erc1155UpdateClaimConditions } from "./write/update-claim-conditions.js";
import { erc1155UpdateTokenMetadata } from "./write/update-token-metadata.js";

export const erc1155Routes = async (fastify: FastifyInstance) => {
  // GET
  await fastify.register(erc1155Get);
  await fastify.register(erc1155GetAll);
  await fastify.register(erc1155GetOwned);
  await fastify.register(erc1155BalanceOf);
  await fastify.register(erc1155IsApproved);
  await fastify.register(erc1155TotalCount);
  await fastify.register(erc1155TotalSupply);
  await fastify.register(erc1155SignatureGenerate);
  await fastify.register(erc1155CanClaim);
  await fastify.register(erc1155GetActiveClaimConditions);
  await fastify.register(erc1155GetAllClaimConditions);
  await fastify.register(erc1155GetClaimerProofs);
  await fastify.register(erc1155GetClaimIneligibilityReasons);

  // POST
  await fastify.register(erc1155airdrop);
  await fastify.register(erc1155burn);
  await fastify.register(erc1155burnBatch);
  await fastify.register(erc1155claimTo);
  await fastify.register(erc1155lazyMint);
  await fastify.register(erc1155mintAdditionalSupplyTo);
  await fastify.register(erc1155mintBatchTo);
  await fastify.register(erc1155mintTo);
  await fastify.register(erc1155SetApprovalForAll);
  await fastify.register(erc1155transfer);
  await fastify.register(erc1155transferFrom);
  await fastify.register(erc1155SignatureMint);
  await fastify.register(erc1155SetClaimCondition);
  await fastify.register(erc1155SetBatchClaimConditions);
  await fastify.register(erc1155UpdateClaimConditions);
  await fastify.register(erc1155UpdateTokenMetadata);
};
