export type ContractExtension =
  | "erc20"
  | "erc721"
  | "erc1155"
  | "marketplace-v3-direct-listings"
  | "marketplace-v3-english-auctions"
  | "marketplace-v3-offers"
  | "roles"
  | "none"
  | "withdraw"
  | "deploy-prebuilt"
  | "deploy-published"
  | "account-factory"
  | "account"
  | "relayer";
